### PR TITLE
Update react-native-camera.podspec

### PR DESCRIPTION
**Pull request by 99uno**
Upgrade MLKit libraries

### CODE REVIEW

**Review by yamifr07 — APPROVED** [review]

**Review by MateusAndrade — APPROVED** [review]

**Comment by MateusAndrade** [comment]
Is this a breaking change?

**Comment by 99uno** [comment]
Yes, its a breaking change because otherwise after updating firebase barcode, text and face recognition subspecs throw an error when doing pod install

**Comment by thomas-blitzm** [comment]
@99uno any reason you closed the request?

**Comment by 99uno** [comment]
Sorry, I know the library must be updated but it means lot of changes in the source code to use the new lib:
[https://developers.google.com/ml-kit/migration/ios](https://developers.google.com/ml-kit/migration/ios)

**Comment by thomas-blitzm** [comment]
all good @99uno 

This means that if the application is using machine learning with react-native-camera, you cannot use the newest version of firebase. Interesting.

**Comment by 99uno** [comment]
There are many issues related to this problem after upgrading Firebase. I decided to use onBarCodeRead for the moment but it should be fixed asap. I tried to update the source code but i'm not an Objective-C expert.

[https://github.com/react-native-camera/react-native-camera/issues/3076](https://github.com/react-native-camera/react-native-camera/issues/3076)
[https://github.com/react-native-camera/react-native-camera/issues/3040](https://github.com/react-native-camera/react-native-camera/issues/3040)

**Comment by thomas-blitzm** [comment]
@99uno unfortunately the clients client likes having barcodes with black background. Which means onBarcodeRead will not be working. 

After a fast check, google is able to understand the barcode, if it is supplied with inverted. 

Now I believe https://www.npmjs.com/package/@react-native-firebase/ml
would fix my issue completely. But something to consider for the future is react-native-camera.

**Comment by rukmanary** [comment]
So @thomas-blitzm we can use react-native-camera to scan barcode on iOS by installing this lib https://www.npmjs.com/package/@react-native-firebase/ml ? is there any other setup or it's ready to go?

**Comment by thomas-blitzm** [comment]
@rukmanary unfortunately that package does not have barcode reader yet implemented into it. Currently they are behind schedule. So if implemented you would pass in an image which it would read and find the barcode. 


https://www.npmjs.com/package/@react-native-firebase/ml-vision
does include barcode, however, it is deprecated and would take some time to implement and make work. 

react-native-camera is currently being upgraded as we speak. So will be interesting to see when they are finished. 

you could try: 
https://github.com/teslamotors/react-native-camera-kit

or a really promising project is this one: https://github.com/cuvent/react-native-vision-camera

but they have not added barcode scanner yet. But hopefully it will finalise soon and add JSI Frame Processors where all machine learning can be written in js.

**Comment by rukmanary** [comment]
@thomas-blitzm I need the camera just to read QR code and Barcode. So, what I need for now is https://github.com/teslamotors/react-native-camera-kit right?

Last year my RN project only build in android and now they want me to build an iOS. I already implemented `react-native-camera` but found this bugs in iOS. So, I hope this library will be upgraded soon

Thanks

**Comment by birken92** [comment]
@rukmanary  What kind of bugs did you find on react-native-camera? 

Onbarcoderead works well for us and I would use that. Tesla one works as well and you can use that package.

**Comment by rukmanary** [comment]
@birken92 I cannot scan barcode in iOS

**Comment by birken92** [comment]
@rukmanary could you show me your code? Just the barcode scanner part

**Comment by rukmanary** [comment]
@birken92

```
 <RNCamera
          style={styles.preview}
          type={RNCamera.Constants.Type.back}
          flashMode={RNCamera.Constants.FlashMode.off}
          captureAudio={false}
          onBarCodeRead={this.onBarCodeRead}>
          <Masking /> // component to cover a whole screen but the center to focus on scanning barcode, it's pretty wide
</RNCamera>
```

it's works perfectly in android for both QR Code and Barcode. But in iOS, it's only works for QR Code

**Comment by thomas-blitzm** [comment]
provide the this.onBarcodeRead as well. 

I assume they might scan the barcode, but your height/width might remove it from the scan. 

Try a console logging every line of scan on an IOS device which includes data.

**Comment by rukmanary** [comment]
@thomas-blitzm I did, but nothing logged. It turns out I forget to add:

```
"pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
'BarcodeDetectorMLKit'
]"
```

But, I came here because I found that line of code makes the pod install error. And I just found a workaround here: https://github.com/react-native-camera/react-native-camera/issues/3043#issuecomment-776386613

in node_modules/react-native-camera/react-native-camera.podspec do this:
```
 s.subspec "BarcodeDetectorMLKit" do |ss|
   ss.dependency 'react-native-camera/RN'
   ss.dependency 'react-native-camera/RCT'
   ss.dependency 'Firebase/MLVision' // delete this
   ss.dependency 'Firebase/MLVisionBarcodeModel' // delete this
   ss.dependency 'GoogleMLKit/BarcodeScanning' // add this one
  end
```

**Pull request closed without merging**
